# Generated by Django 6.0 on 2025-12-25 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('authors', models.CharField(blank=True, max_length=512)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('domain', models.CharField(choices=[('CAD', 'CAD'), ('CAM', 'CAM'), ('CFD', 'CFD'), ('FEA', 'FEA')], max_length=10)),
                ('file_path', models.TextField()),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('ingestion_status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('domain_filter', models.CharField(blank=True, max_length=10)),
                ('top_k', models.IntegerField()),
                ('retrieved_chunks', models.IntegerField()),
                ('rerank_applied', models.BooleanField(default=False)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_strategy', models.CharField(max_length=64)),
                ('chunk_size', models.IntegerField()),
                ('overlap', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='rag.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('page_start', models.IntegerField(blank=True, null=True)),
                ('page_end', models.IntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=256)),
                ('chunk_strategy', models.CharField(max_length=64)),
                ('chunk_index', models.IntegerField()),
                ('embedding_model', models.CharField(max_length=128)),
                ('vector_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.paper')),
            ],
            options={
                'indexes': [models.Index(fields=['paper', 'chunk_strategy'], name='rag_chunk_paper_i_dd4fd8_idx')],
            },
        ),
    ]
